version: '3.3'
services:
  common-mysql-db:
    image: 'mysql:8.0.16'
    container_name: common-mysql-db
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      #- './mysql/mysql:/var/lib/mysql'
      - './config/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './local_data/mysql_data:/usr/local/share/data'
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: common-files-upload
      MYSQL_PASSWORD: common-files-upload_123456
      MYSQL_DATABASE: db_common-files-upload

  common-redis:
    image: 'redis:6.0.10'
    container_name: common-redis
    ports:
      - 6379:6379
    expose:
      - 6379

  common-files-upload-files:
    image: 'registry.xxx.cn/xxx/common-files-upload-files:dev_v1'
    container_name: common-files-upload-files
    tty: true
    volumes:
      - '.:/opt/app'
    ports:
      - 9080:9080
    links:
      - common-mysql-db
#      - common-redis
    depends_on:
      - common-mysql-db
#      - common-redis
    environment:
      MYSQL_HOST: common-mysql-db
      MYSQL_PORT: 3306
      MYSQL_USER: common-files-upload
      MYSQL_PASSWORD: common-files-upload_123456
      MYSQL_DATABASE: db_common-files-upload

networks:
  common-files-upload-files:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.25.1/16
