apiVersion: v1
kind: Service
metadata:
  name: common-files
  namespace: default
  labels:
    app: common-files
    service: common-files
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: common-files
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-files
  namespace: default
  labels:
    app: common-files
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-files
  template:
    metadata:
      labels:
        app: common-files
    spec:
      serviceAccountName: common-files
      containers:
      - name: common-files
        image: ccr.ccs.tencentyun.com/game-center/common-files:staging_v0.0.2
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9080
        volumeMounts:
          - name: upload-data
            mountPath: /upload/
      volumes:
        - name: upload-data
          persistentVolumeClaim:
            claimName: common-files-pv-claim
