apiVersion: v1
kind: Service
metadata:
  name: common-files
  namespace: unicorn-stage
  labels:
    app: common-files
    service: common-files
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: common-files
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      diskSelector: ""
      migratable: "false"
      nodeSelector: ""
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
    volumeHandle: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-files-v1
  namespace: unicorn-stage
  labels:
    app: common-files
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-files
      version: v1
  template:
    metadata:
      labels:
        app: common-files
        version: v1
    spec:
      serviceAccountName: common-files
      containers:
        - name: common-files
          image: harbor.5qipa.com:6443/games/common-files:staging_v0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
        volumeMounts:
          - name: data
            mountPath: /opt/public/upload/
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: test
---
