server:
  host: 0.0.0.0
  port: :9080
db:
  db_enable: false
  name: db_commonFiles
  addr: localhost:3306
  username: root
  password: mustang
  gorm:
    logMode: 0
    maxOpenConn: 200
    maxIdleConn: 0
    singularTable: 1
log:
  level: debug
  maxsize: 1024
  maxage: 30
  maxbackups: 10
  localtime: 1
  compress: 1
  fileName: common-files-upload.log
api:
  version: /api/v1
jwt:
  secret: vz5(#pfnf+#p5ok&d2yrqd#)k0jz!#tb*$=^c5nl0(z+0=p5!9
web3:
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweEE2QTMyZUE5ZmJEM2QzNEM5N0VhMWE5ODEyNzFGMmI5ZGUyMDQ4ODkiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2NTIyNTA1NjUyNjUsIm5hbWUiOiJ0ZXN0In0.mGBeVC5bN0vkkQOZvTxwe1eYrmrXtlYVIJZJxpkz_g8
email:
  server: partner.outlook.cn
  sender: eim@xxx.com
  password: abc!@#456
  port: 587
  security: true

#  访问静态文件路径
uploadUrl: /api/v1/upload/
#  上传文件路径
filePath: ./upload/
