server:
  host: 0.0.0.0
  port: :9080
db:
  name: db_common-files-upload
  addr: mysqldb
  username: root
  password: xxx
  gorm:
    logMode: 0
    maxOpenConn: 2000
    maxIdleConn: 0
    singularTable: 1
log:
  level: info
  maxsize: 500
  maxage: 30
  maxbackups: 200
  localtime: 1
  compress: 1
  fileName: common-files-upload.log
api:
  version: /api/v1
jwt:
  secret: vz5(#pfnf+#p5ok&d2yrqd#)k0jz!#tb*$=^c5nl0(z+0=p5!9
email:
  server: partner.outlook.cn
  sender: eim@xxx.com
  password: xxx
  port: 587
  security: true
baseUrl: https://my.xxx.cn/
uploadUrl:  https://my.xxx.cn/api/common-files-upload/v1/upload/
filePath: /opt/public/upload/
